### ISSUE TITLE
[week1] 질문 정리 완료했습니다. 

### ISSUE THREAD

**Issue by Sooooyeon** [Sooooyeon/Preparing-Interview#5]
1주차 질문 정리 완료했습니다 : )

호이스팅 답변 부분에서 parser에 대한 내용을 조금 더 추가해야할지.. 의견 부탁드리겠습니다..!!
(해지님께서 참고하신 링크를 아래에 첨부해주셔도 좋을 것 같습니다!)

추가로 들어가야 할 내용이 있다고 느껴지시면 이슈 새로 만들어서 작성 부탁드리겠습니다🙂
@AYFG @LeeeeHaeji 

++
새해 복 많이 받으세요!! 햎삐뉴이어!!🐲

**Comment by AYFG** [comment]
감사합니당!!! parser는 추가하지 않는게 담백하지 않을까 싶은 의견 올립니다..!
새해 복 많이 받으세요 고생하셨습니다!!!
